[project]
name = "icondrawer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.2",
    "pyside6>=6.8.3",
]
